version: '2'
volumes:
  redis:
    driver: local
  educadex:
    driver: local
services:
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - redis:/var/lib/redis
    networks:
      - default
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    environment:
      - SECRET_KEY=$SECRET_KEY
    volumes:
      - educadex:/var/www/educadex
    networks:
      - default
    depends_on:
      - redis
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`educadex.inf.ufsm.br`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.docker.network=traefik"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - educadex:/var/www/educadex
    networks:
      - traefik
      - default
    depends_on:
      - php-fpm
networks:
  traefik:
    external:
      name: traefik
