FROM php:fpm-alpine
WORKDIR /var/www/educadex
COPY --chown=nobody:nobody . /var/www/educadex
RUN chown nobody:nobody /var/www/educadex

RUN apk add postgresql-dev
RUN docker-php-ext-install bcmath mbstring pdo pdo_pgsql
RUN curl -sL https://getcomposer.org/installer | php -- --install-dir /usr/bin --filename composer
RUN sed -i 's/www-data/nobody/' /usr/local/etc/php-fpm.d/www.conf
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

RUN apk add g++ make autoconf
RUN adduser -D php
RUN composer install --no-dev --no-cache --prefer-dist --no-interaction
RUN sed -i 's/nobody/php/' /usr/local/etc/php-fpm.d/www.conf
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

VOLUME /var/www/educadex

ENV PHP_IDE_CONFIG "serverName=docker"
ENV XDEBUG_CONFIG "remote_enable=1 remote_autostart=1 remote_host=host.docker.internal"

CMD ["php-fpm"]

EXPOSE 9000
